---
language: python
services: docker

env:
  - MOLECULE_DISTRO: debian9
  - MOLECULE_DISTRO: ubuntu1604
  - MOLECULE_DISTRO: ubuntu1804

install:
  - mv ../ansible-role-paperless ../ovv.paperless
  - pip install molecule docker

script:
  - molecule test
